package fqme.model;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import fqme.column.Column;
import fqme.column.common.NumericColumn;
import fqme.connection.DBConfig;
import lombok.Getter;
import lombok.Setter;

/**
 * ORM model realization.
 */
public abstract class Model<T extends Model<T>> {
    /**
     * Autogenerated id.
     */
    @Getter @Setter
    private Optional<Integer> id = Optional.empty();
    public static final NumericColumn<Integer> id_ = new NumericColumn<>("id");

    /**
     * Map with meta info (table names, fields, etc.)
     * for Model subclasses.
     */
    private static HashMap<Class<? extends Model<?>>, ModelMetaInfo> modelsMetaInfo = new HashMap<>();

    /**
     * Build and store model subclass meta info.
     *
     * @param modelClass model subclass
     * @param configPath path to config file
     */
    public static void register(Class<? extends Model<?>> modelClass, DBConfig dbConfig)
            throws NoSuchFieldException, IllegalAccessException {
        String tableName = modelClass.getSimpleName().replaceFirst("Model$", "").toLowerCase();
        // get all fields of model class
        Field[] classFields = modelClass.getDeclaredFields();
        List<String> columnsNames = new ArrayList<>();
        // list of fields types
        List<Class<?>> fieldsTypesList = new ArrayList<>();
        // map with columns names as keys and their types as values
        Map<String, Class<?>> columnsTypes = new HashMap<>();
        // map with models fields that contains columns data
        Map<String, Field> fields = new HashMap<>();
        // iterate over all fields
        for (Field field : classFields) {
            if (Column.class.isAssignableFrom(field.getType())) {
                Column<?> column = (Column<?>) field.get(null);
                // add name of Column
                columnsNames.add(column.getName());

                // add type of field
                Field modelField = modelClass.getDeclaredField(column.getName());
                Class<?> fieldType = modelField.getType();
                fieldsTypesList.add(fieldType);

                // add field to dataFields
                fields.put(column.getName(), modelField);

                // add column type
                columnsTypes.put(column.getName(), fieldType);
            }
        }
        Class<?>[] fieldsTypes = new Class<?>[fieldsTypesList.size()];
        for (int i = 0; i < fieldsTypesList.size(); i++) {
            fieldsTypes[i] = fieldsTypesList.get(i);
        }
        // store model subclass meta info
        ModelMetaInfo metaInfo = new ModelMetaInfo(tableName, columnsNames, columnsTypes, fieldsTypes, fields,
                dbConfig);
        modelsMetaInfo.put(modelClass, metaInfo);
    }

    /**
     * Get model subclass meta info.
     *
     * @param modelClass model subclass
     * @return model subclass meta info
     */
    public static ModelMetaInfo getModelMetaInfo(Class<? extends Model<?>> modelClass) {
        return Model.modelsMetaInfo.get(modelClass);
    }

    /**
     * Initialize model from objects array with values of fields in proper order.
     * Use for instantiating from ResultSet
     *
     * @see View
     *
     * @param objects    Array of fields values
     * @param modelClass subclass of Model
     * @return Model instance
     */
    public static <K extends Model<K>> K fromFieldsValues(Object[] objects, Class<K> modelClass) throws Exception {
        ModelMetaInfo metaInfo = Model.getModelMetaInfo(modelClass);
        Constructor<K> constructor = modelClass.getConstructor(metaInfo.getFieldsTypes());
        return constructor.newInstance(objects);
    }
}
